# Generated by Django 5.0.2 on 2024-02-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_Age',
            fields=[
                ('pk_age', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_Date',
            fields=[
                ('pk_date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_Federation',
            fields=[
                ('pk_federation', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('federation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='D_Geographie',
            fields=[
                ('pk_geographie', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('commune', models.CharField(max_length=50)),
                ('qpv', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=50)),
                ('nom_departement', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('status_geo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='D_Sexe',
            fields=[
                ('pk_sexe', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='D_Type',
            fields=[
                ('pk_type', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('code_qpv', models.CharField(max_length=255)),
                ('nom_qpv', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('statut_geo', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('federation', models.CharField(max_length=255)),
                ('clubs', models.CharField(max_length=255)),
                ('epa', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ODS_lic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('code_qpv', models.CharField(max_length=255)),
                ('nom_qpv', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('statut_geo', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('federation', models.CharField(max_length=255)),
                ('f_1_4_ans', models.CharField(default='0', max_length=255)),
                ('f_5_9_ans', models.CharField(default='0', max_length=255)),
                ('f_10_14_ans', models.CharField(default='0', max_length=255)),
                ('f_15_19_ans', models.CharField(default='0', max_length=255)),
                ('f_20_24_ans', models.CharField(default='0', max_length=255)),
                ('f_25_29_ans', models.CharField(default='0', max_length=255)),
                ('f_30_34_ans', models.CharField(default='0', max_length=255)),
                ('f_35_39_ans', models.CharField(default='0', max_length=255)),
                ('f_40_44_ans', models.CharField(default='0', max_length=255)),
                ('f_45_49_ans', models.CharField(default='0', max_length=255)),
                ('f_50_54_ans', models.CharField(default='0', max_length=255)),
                ('f_55_59_ans', models.CharField(default='0', max_length=255)),
                ('f_60_64_ans', models.CharField(default='0', max_length=255)),
                ('f_65_69_ans', models.CharField(default='0', max_length=255)),
                ('f_70_74_ans', models.CharField(default='0', max_length=255)),
                ('f_75_79_ans', models.CharField(default='0', max_length=255)),
                ('f_80_99_ans', models.CharField(default='0', max_length=255)),
                ('f_nr', models.CharField(default='0', max_length=255)),
                ('h_1_4_ans', models.CharField(default='0', max_length=255)),
                ('h_5_9_ans', models.CharField(default='0', max_length=255)),
                ('h_10_14_ans', models.CharField(default='0', max_length=255)),
                ('h_15_19_ans', models.CharField(default='0', max_length=255)),
                ('h_20_24_ans', models.CharField(default='0', max_length=255)),
                ('h_25_29_ans', models.CharField(default='0', max_length=255)),
                ('h_30_34_ans', models.CharField(default='0', max_length=255)),
                ('h_35_39_ans', models.CharField(default='0', max_length=255)),
                ('h_40_44_ans', models.CharField(default='0', max_length=255)),
                ('h_45_49_ans', models.CharField(default='0', max_length=255)),
                ('h_50_54_ans', models.CharField(default='0', max_length=255)),
                ('h_55_59_ans', models.CharField(default='0', max_length=255)),
                ('h_60_64_ans', models.CharField(default='0', max_length=255)),
                ('h_65_69_ans', models.CharField(default='0', max_length=255)),
                ('h_70_74_ans', models.CharField(default='0', max_length=255)),
                ('h_75_79_ans', models.CharField(default='0', max_length=255)),
                ('h_80_99_ans', models.CharField(default='0', max_length=255)),
                ('h_nr', models.CharField(default='0', max_length=255)),
                ('nr_nr', models.CharField(default='0', max_length=255)),
                ('total', models.CharField(default='0', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='F_Club',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
                ('fk_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('fk_federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_federation')),
                ('fk_geographie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_geographie')),
                ('fk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_type')),
            ],
        ),
        migrations.CreateModel(
            name='F_Licence',
            fields=[
                ('code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
                ('age_group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_age')),
                ('date_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('federation_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_federation')),
                ('geography_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_geographie')),
                ('sexe_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_sexe')),
            ],
        ),
    ]
