# Generated by Django 5.0.2 on 2024-02-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_geographie',
            name='code_commune',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='d_geographie',
            name='code_qpv',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
