# Generated by Django 5.0.2 on 2024-02-16 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ods_lic'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Age',
            fields=[
                ('pk_age', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_Date',
            fields=[
                ('pk_date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_Federation',
            fields=[
                ('pk_federation', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('federation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='D_Geographie',
            fields=[
                ('pk_geographie', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('code_commune', models.CharField(max_length=30)),
                ('code_qpv', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('qpv', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=50)),
                ('nom_departement', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('status_geo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='D_Sexe',
            fields=[
                ('pk_sexe', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='D_Type',
            fields=[
                ('pk_type', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='F_Club',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
                ('fk_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('fk_federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_federation')),
                ('fk_geographie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_geographie')),
                ('fk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_type')),
            ],
        ),
    ]
