# Generated by Django 5.0.2 on 2024-02-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ods_lic'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_date', models.DateField()),
            ],
        ),
    ]
