# Generated by Django 5.0.2 on 2024-02-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_d_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Age',
            fields=[
                ('pk_age', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
