# Generated by Django 5.0.2 on 2024-02-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_d_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Sexe',
            fields=[
                ('pk_sexe', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
