# Generated by Django 5.0.2 on 2024-02-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_d_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Federation',
            fields=[
                ('pk_federation', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('federation', models.CharField(max_length=255)),
            ],
        ),
    ]
