# Generated by Django 5.0.2 on 2024-02-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_d_federation'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Type',
            fields=[
                ('pk_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
