# Generated by Django 5.0.2 on 2024-02-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_d_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Geographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(max_length=30)),
                ('code_qpv', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('qpv', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=50)),
                ('nom_departement', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('status_geo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='d_geographie',
            constraint=models.UniqueConstraint(fields=('code_commune', 'code_qpv'), name='pk_geographie'),
        ),
    ]
