# Generated by Django 5.0.2 on 2024-02-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_d_geographie_d_geographie_pk_geographie'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fk_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('fk_federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_federation')),
                ('fk_geographie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_geographie')),
                ('fk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_type')),
            ],
        ),
        migrations.AddConstraint(
            model_name='f_club',
            constraint=models.UniqueConstraint(fields=('fk_date', 'fk_geographie', 'fk_federation', 'fk_type'), name='pk_club'),
        ),
    ]
